<?php

namespace Admin\Repository;

/**
 * AduserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AduserRepository extends \Doctrine\ORM\EntityRepository
{
}
