<?php

namespace User\Repository;

/**
 * ForgetpswRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForgetpswRepository extends \Doctrine\ORM\EntityRepository
{
}
