<?php

namespace User\Repository;

use User\Entity\User;
// use Pagerfanta\Adapter\DoctrineORMAdapter;
// use Pagerfanta\Pagerfanta;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function querysearch($state)
	{
		if($state=='')
		{
			return $this->getEntityManager()
	            ->createQuery('
	                SELECT u
	                FROM UserBaseBundle:User u
	                ORDER BY u.id DESC
	            ');
		}else{
			return $this->getEntityManager()
	            ->createQuery('
	                SELECT u
	                FROM UserBaseBundle:User u
	                WHERE u.state = :state
	                ORDER BY u.id DESC
	            ')->setParameter('state', $state)
	        ;
		}
	}

	public function page($page = 1,$state='')
	{
		// $paginator = new Pagerfanta(new DoctrineORMAdapter($this->querysearch($state), false));
  //       $paginator->setMaxPerPage(User::NUM_ITEMS);
  //       $paginator->setCurrentPage($page);

  //       return $paginator;
	}

}
